### ISSUE TITLE
Send OTP not working with ajax call

### ISSUE THREAD

**Issue by Srinucnu** [MSG91/sendotp-php#1]
I tried to send otp using ajax call, but am getting an error in console like "500 Internal Server Error". 

When am trying without an ajax call it's working fine.

**Comment by rwalkover** [comment]
Calling directly via Ajax is not recommended as there are chances to explore Auth secret over network request.
We suggest you to better use server to server communication.

If still need help please contact support over chat or dropping an email to support@msg91.com
