### ISSUE TITLE
this package not found in laravel

### ISSUE THREAD

**Issue by Raghuveersingh** [MSG91/sendotp-php#2]
I am getting following error
> $composer require sendotp/sendotp

 [InvalidArgumentException]                                                   
  Could not find package sendotp/sendotp at any version for your minimum-stab  
  ility (stable). Check the package spelling or your minimum-stability

**Comment by rwalkover** [comment]
Package added on Packagist now you can run composer.

**Comment by Raghuveersingh** [comment]
one more bug in your code
in sendotp.php file and function call()  the line no 134 are
        $httpInstance->setParameters($this->message, $this->key, $args);
so line should be
        $httpInstance->setParameters($this->messageTemplate, $this->key, $args);

you used $this->messageTemplate in constructor so $this->message showing undefined error.

**Comment by rwalkover** [comment]
You can contact support @ support@msg91.com or use chat option.
You are free to report it here too.
